# Example agent types YAML
- name: "Worker"
  type: "worker"
  color: "#FF7043"   # Vibrant orange
  move_speed: 2.0
  strength: 5
  stamina: 100
  vision: 6
  work_rate: 5
  icon: "W"
  damping: 0.85
  move_probability: 1.0
  hunger_rate: 0.04
  hunger_threshold: 50.0
  movement_profile:
    Mountain: "Slow(2.0)"   # Moves at half speed on mountains (2x slower)
- name: "Scout"
  type: "scout"
  color: "#D81B60"   # Bright magenta
  move_speed: 4.0
  strength: 2
  stamina: 60
  vision: 12
  work_rate: 3
  icon: "S"
  damping: 0.85
  move_probability: 1.0
  hunger_rate: 0.02
  hunger_threshold: 40.0
  movement_profile:
    Mountain: "Slow(1.5)"   # Moves at 2/3 speed on mountains (1.5x slower)
- name: "Soldier"
  type: "soldier"
  color: "#00B8D4"   # Cyan
  move_speed: 3.0
  strength: 8
  stamina: 80
  vision: 8
  work_rate: 2
  icon: "X"
  damping: 0.95
  move_probability: 0.7
  hunger_rate: 0.06
  hunger_threshold: 45.0
  movement_profile:
    Mountain: "Slow(3.0)"   # Moves at 1/3 speed on mountains (3x slower)
- name: "Miner"
  type: "miner"
  color: "#FFEB3B"   # Lemon yellow
  move_speed: 2.0
  strength: 7
  stamina: 90
  vision: 6
  work_rate: 7
  icon: "M"
  damping: 0.95
  move_probability: 0.5
  hunger_rate: 0.02
  hunger_threshold: 38.0
  movement_profile:
    Mountain: "Slow(1.2)"   # Moves at 5/6 speed on mountains (1.2x slower)
- name: "Farmer"
  type: "farmer"
  color: "#8E24AA"   # Violet
  move_speed: 2.0
  strength: 3
  stamina: 100
  vision: 7
  work_rate: 8
  icon: "F"
  damping: 0.95
  move_probability: 0.5
  hunger_rate: 0.01
  hunger_threshold: 42.0
  movement_profile:
    Mountain: "Normal"   # Not slowed on mountains
- name: "Builder"
  type: "builder"
  color: "#4CAF50"   # Green
  move_speed: 2.0
  strength: 6
  stamina: 95
  vision: 7
  work_rate: 9
  icon: "B"
  damping: 0.95
  move_probability: 0.5
  hunger_rate: 0.02
  hunger_threshold: 42.0
  movement_profile:
    Mountain: "Slow(1.8)"   # Moves at ~55% speed on mountains (1.8x slower)
- name: "Doctor"
  type: "doctor"
  color: "#9C27B0"   # Deep purple
  move_speed: 3.0
  strength: 2
  stamina: 85
  vision: 10
  work_rate: 10
  icon: "+"
  damping: 0.85
  move_probability: 1.0
  hunger_rate: 0.01
  hunger_threshold: 40.0
  movement_profile:
    Mountain: "Slow(2.5)"   # Moves at 40% speed on mountains (2.5x slower)
