# Example explicit spawn config for use with custom_demo profile
map:
  width: 100
  height: 100

agents:
  - type: worker
    pos: { x: 10, y: 20 }
    count: 3
  - type: scout
    pos: { x: 30, y: 40 }
    count: 2

food:
  - pos: { x: 15, y: 25 }
    count: 5

items:
  - type: medkit
    pos: { x: 50, y: 60 }
    count: 1

money:
  - pos: { x: 80, y: 80 }
    amount: 100
    count: 2
